{"author":{"id":"1c0be4c7efe4cf70011d270a87e33999699eb0e9a5b12f84e0369f90dae3dacd"},"ops":[{"type":3,"timestamp":1618088808,"nonce":"LYo1gU0ga1i2bCyy77yhDZVpJf8=","metadata":{"github-id":"MDEyOklzc3VlQ29tbWVudDgxNzIwMjI0Nw==","github-url":"https://github.com/git-bug/git-bug/issues/629#issuecomment-817202247"},"message":"To me it seems that the error is not in the github bridge but somewhere else. So, no, it's not fixed. It has been introduced somewhere between 01b9490 and bc5f618. I tried to bisect it, but was not successful in locating it yet.","files":null},{"type":3,"timestamp":1618166238,"nonce":"kTSdmmi0MO1fH2+BQNsD2kaszQM=","metadata":{"github-id":"MDEyOklzc3VlQ29tbWVudDgxNzM1Mjg4OQ==","github-url":"https://github.com/git-bug/git-bug/issues/629#issuecomment-817352889"},"message":"I think I found the problem. I will send you a PR soon.","files":null}]}