{"author":{"id":"3998add589f6a09cf4bdf0e85e5481d2c48b8a757edd699a79a0c929ab5005db"},"ops":[{"type":3,"timestamp":1669196687,"nonce":"9dFjeggXFuOphIxiPFDV1r2P4mk=","metadata":{"github-id":"IC_kwDOCGKeh85O9qI3","github-url":"https://github.com/git-bug/git-bug/issues/749#issuecomment-1324786231"},"message":"I meant that it's a transient failure on github side, meaning that the exact same request would succeed later, meaning that git-bug is doing a valid request.\n\nThe problem is in how we handle those random failure.","files":null}]}