{"author":{"id":"844b38486e9243385d79a9bda290290489e6c56956835ce89a8ecda489d00a44"},"ops":[{"type":1,"timestamp":1552483500,"nonce":"0N8RUCz11ux7dH6L+D2RWl3daqo=","metadata":{"github-id":"MDU6SXNzdWU0MjA0OTc3OTM=","github-url":"https://github.com/git-bug/git-bug/issues/103","origin":"github"},"title":"Cannot pull identities/bugs from raw repository","message":"Bellow is a series of commands that:\n1. create a bare repository\n2. creates a local repository\n3. creates a commit, an identity, and a bug, and pushes them to the bare repository created in step 1.\n4. clones the bare repository\n5. tries to pull the identities/bugs\n\n```\ncd /tmp\nmkdir -p git-bug-bug/bare git-bug-bug/repo\ncd git-bug-bug/bare \u0026\u0026 git init --bare\ncd ../repo \u0026\u0026 git init\necho \"Hello World\" \u003e README\ngit add .\ngit commit -m \"initial commit\"\ngit remote add origin ../bare\ngit push origin master\ngit bug user create\ngit bug add # fill in some title and description\ngit bug push\ncd ..\ngit clone bare clonedrepo\ncd clonedrepo\ngit bug pull\n```\n\nAt the very last step I get the following output:\n\n```\nBuilding identity cache... Done.\nBuilding bug cache... Done.\nFetching remote ...\n\n\nMerging data ...\n8e86a36: invalid data: remote bug is not readable: identity doesn't exist\n```\n\nCreating an identity before `git bug pull` still produces an error.\n\nHere's my go env variables\n```\ngo version go1.12 darwin/amd64\nGOARCH=\"amd64\"\nGOBIN=\"\"\nGOEXE=\"\"\nGOFLAGS=\"\"\nGOHOSTARCH=\"amd64\"\nGOHOSTOS=\"darwin\"\nGOOS=\"darwin\"\nGOPROXY=\"\"\nGORACE=\"\"\nGOROOT=\"/usr/local/Cellar/go/1.12/libexec\"\nGOTMPDIR=\"\"\nGOTOOLDIR=\"/usr/local/Cellar/go/1.12/libexec/pkg/tool/darwin_amd64\"\nGCCGO=\"gccgo\"\nCC=\"clang\"\nCXX=\"clang++\"\nCGO_ENABLED=\"1\"\nGOMOD=\"\"\nGOROOT/bin/go version: go version go1.12 darwin/amd64\nGOROOT/bin/go tool compile -V: compile version go1.12\nuname -v: Darwin Kernel Version 16.6.0: Fri Apr 14 16:13:31 PDT 2017; root:xnu-3789.60.24~4/RELEASE_X86_64\nProductName:\tMac OS X\nProductVersion:\t10.12.5\nBuildVersion:\t16F2073\nlldb --version: lldb-370.0.42\n  Swift-3.1\n```\n\nAnd here's my git version\n```\ngit version 2.20.1\n```\n\nPlease let me know if I forgot to provide any more information.\n\nI managed to recreate the issue on multiple machines: a mac, an ubuntu, and an archlinux machines. I did not have time to debug the issue though.","files":null}]}