{"author":{"id":"51fe4f1d89f7410a02e86ff62212c6ca3942dfa4b75e005308889a1ec56f9fa0"},"ops":[{"type":3,"timestamp":1672232569,"nonce":"IDGHkC1dM52O2zuA0+k+LTYxe5U=","metadata":{"github-id":"IC_kwDOCGKeh85RdTkw","github-url":"https://github.com/git-bug/git-bug/issues/934#issuecomment-1366636848"},"message":"That worked. I have the same authentication error with git-bug push/pull, though.","files":null}]}