{"author":{"id":"c63f70c3d797d1c7b6ed566d510a7f73681c3bd0c557ab6d5086a193a026cb02"},"ops":[{"type":3,"timestamp":1594906149,"nonce":"u3LVozoso2sXJ4Vn0o3kZ2/qKdU=","metadata":{"github-id":"MDEyOklzc3VlQ29tbWVudDY1OTQxMjIzOQ==","github-url":"https://github.com/git-bug/git-bug/issues/366#issuecomment-659412239"},"message":"\u003e Hi, I am receiving the same panic: runtime error: index out of range [-1] on the repo that I used for testing in #360.\n\nI think it is related to https://github.com/MichaelMure/git-bug/pull/378 cause it works perfectly when you add a first issue on gitlab.\n\nBtw, there is any steps done about this gitlab gridge? \n\nI'll clone my other issue cause it is just a duplicate of this : https://github.com/MichaelMure/git-bug/issues/389","files":null},{"type":6,"timestamp":1594906156,"nonce":"m+VvipCKxwde13z7sEBhDzTpzhk=","metadata":{"github-id":"MDE1OlVzZXJDb250ZW50RWRpdElzc3VlQ29tbWVudEVkaXQ6Mzg2MzA1NDQw"},"target":"d77bb686e88716a03793c7a82439c2a8ead5221fdcbbdc227a0037e96792c77d","message":"\u003e Hi, I am receiving the same panic: runtime error: index out of range [-1] on the repo that I used for testing in #360.\n\nI think it is related to https://github.com/MichaelMure/git-bug/pull/378 cause it works perfectly when you add a first issue on gitlab.\n\nBtw, there is any steps done about this gitlab gridge? \n\nI'll close my other issue cause it is just a duplicate of this : https://github.com/MichaelMure/git-bug/issues/389","files":null}]}