{"author":{"id":"3998add589f6a09cf4bdf0e85e5481d2c48b8a757edd699a79a0c929ab5005db"},"ops":[{"type":3,"timestamp":1668964263,"nonce":"NzovPC+uLOl4R3FCPwof7JKOosU=","metadata":{"github-id":"IC_kwDOCGKeh85Ov77E","github-url":"https://github.com/git-bug/git-bug/issues/609#issuecomment-1321189060"},"message":"Anybody knows if that's still an issue, especially in the newly released v0.8.0 ?","files":null},{"type":5,"timestamp":1668964273,"nonce":"V69hceMHyFiYXNURE+Ius3r+ryo=","metadata":{"github-id":"LE_lADOCGKeh84yPOGNzwAAAAHUActA"},"added":["area/bridge"],"removed":[]}]}