{"author":{"id":"2448fcf9bb2f5cc11dd08a08618a7b375c1db93aef84885cf46f8718e5622232"},"ops":[{"type":1,"timestamp":1616993052,"nonce":"i8ZH9zTPZU8vV4HymsE/ae9MhHQ=","metadata":{"github-id":"MDU6SXNzdWU4NDI5NjAzMDU=","github-url":"https://github.com/git-bug/git-bug/issues/610","origin":"github"},"title":"Dependabot can't resolve your Go dependency files","message":"Dependabot can't resolve your Go dependency files.\n\nAs a result, Dependabot couldn't update your dependencies.\n\nThe error Dependabot encountered was:\n\n```\ngithub.com/MichaelMure/git-bug/commands: cannot find module providing package github.com/MichaelMure/git-bug/commands\n```\n\nIf you think the above is an error on Dependabot's side please don't hesitate to get in touch - we'll do whatever we can to fix it.\n\n[View the update logs](https://app.dependabot.com/accounts/MichaelMure/update-logs/74181731).","files":null}]}