{"author":{"id":"6ade287c670d26a23a08cda3d2265a954b39f2ebac40072afffe5646f4a6ff2c"},"ops":[{"type":3,"timestamp":1675370840,"nonce":"v3g9xulMPCIDZU9eBzhCV4gGMB0=","metadata":{"github-id":"IC_kwDOCGKeh85UTUzE","github-url":"https://github.com/git-bug/git-bug/issues/1014#issuecomment-1414352068"},"message":"Sorry, finally I made a reboot : it works now, but I don't know how to reproduce... So issue could be closed.\nI'll try a few tests, and then I'll send you a feedback if it succeeds.","files":null},{"type":4,"timestamp":1675370840,"nonce":"Fv3xlucBVpf09QcB+OymWj48+XE=","metadata":{"github-id":"CE_lADOCGKeh85dK9uAzwAAAAH2MZiJ"},"status":2},{"type":3,"timestamp":1675373379,"nonce":"cuOzkpBAYoIjnpBKcsZZWFINSkw=","metadata":{"github-id":"IC_kwDOCGKeh85UTgLk","github-url":"https://github.com/git-bug/git-bug/issues/1014#issuecomment-1414398692"},"message":"Here I reproduced:\nFirst, you run git-bug: here `.git/git-bug/lock` contains the PID (ex.: 1322).\nThe save all your works and close all youre running tasks (but you don't close git-bug).\nNow if you hard-reboot (pressing \"Off\" button a long time) while running git-bug, then git-bug is killed and `.git/git-bug/lock` isn't deleted (containing the killed PID: 1322).\nNow you reboot, but you don't start with git-hub : you run another programms and don't close them, until those PID's are greater than the killed PID (ex.: you can launch chromium and open a large number of tabs).\nWith (un)luck, it will open a process with the same PID (1322).\nThen you launch git-hub, and it's reproduced (ex.: `Error: the repository you want to access is already locked by the process pid 1322`).\nThe first time I reported it, I was realy unlucky: after hard-reboot, I think the \"killed PID\" was owned by a system's process so it wasn't listed with `ps -e`.\nMay I should test the PID's name to ? If the PID is found, then whe check this PID's name. And if the PID's name is \"git-bug\", then git-bug isn't lauch, else git-bug could be launched.","files":null},{"type":6,"timestamp":1676830783,"nonce":"yuAeUEFyf2I8IZox18fqEAGeic8=","metadata":{"github-id":"UCE_lALOCGKeh85UTgLkzi19v0g"},"target":"c90d7d6d974e291798bd117c8124e48a9672182f4ebee277d6dbe1a363d92502","message":"Here I reproduced:\nFirst, you run git-bug: here `.git/git-bug/lock` contains the PID (ex.: 1322).\nThe save all your works and close all youre running tasks (but you don't close git-bug).\nNow if you hard-reboot (pressing \"Off\" button a long time) while running git-bug, then git-bug is killed and `.git/git-bug/lock` isn't deleted (containing the killed PID: 1322).\nNow you reboot, but you don't start with git-hub : you run another programms and don't close them, until those PID's are greater than the killed PID (ex.: you can launch chromium and open a large number of tabs).\nWith (un)luck, it will open a process with the same PID (1322).\nThen you launch git-hub, and it's reproduced (ex.: `Error: the repository you want to access is already locked by the process pid 1322`).\nThe first time I reported it, I was realy unlucky: after hard-reboot, I think the \"killed PID\" was owned by a system's process so it wasn't listed with `ps -e`.\nMay it should test the PID's name to ? If the PID is found, then we check this PID's name. And if the PID's name is \"git-bug\", then git-bug isn't launched, else git-bug could be launched.","files":null},{"type":4,"timestamp":1675373380,"nonce":"U0n8w7Q8mU7JMA3cAUkvWOmbN5o=","metadata":{"github-id":"REE_lADOCGKeh85dK9uAzwAAAAH2Nn-T"},"status":1}]}