{"author":{"id":"213185e7e3687782a663bad20a76bed1a8184de2c6bb3fb9030b9b21cd24a213"},"ops":[{"type":1,"timestamp":1743866495,"nonce":"xHue2khAUa3b38JWROQWISDFnjk=","metadata":{"github-id":"I_kwDOCGKeh86xR-iU","github-url":"https://github.com/git-bug/git-bug/issues/1335","origin":"github"},"title":"\"git bug push\" fails with \"Error: repository not found\" when using custom SSH configuration","message":"When i attempt to execute `git bug push`, it fails with the following error:\n```\nError: repository not found\n```\nI am working with a remote git server accessible via ssh, and I define the connection configuration in `.ssh/config` like this (data is mangled):\n```\nHost privategit\n    Hostname 8.8.8.8\n    Port 4242\n    IdentityFile ~/.ssh/dev@lab\n    User git\n```\nMy git origin looks like this:\n```\n$ git remote get-url origin\nprivategit:my-project\n```\nI suspect this issue is related to #944, which dealt with ignoring `insteadOf` configurations. However, in my case, the issue appears to be related to git-bug **ignoring SSH configurations defined in `~/.ssh/config`**. The standard Git CLI works fine with the configuration, but `git-bug` seems unable to use it.","files":null}]}