{"author":{"id":"089e58453f87fc11fe2de1fa10bdb98260b5e201b722013c9439f871aa147c5f"},"ops":[{"type":3,"timestamp":1674485626,"nonce":"qbCUVeu4qPWB2CThid0hCpGP6HU=","metadata":{"github-id":"IC_kwDOCGKeh85Tea6z","github-url":"https://github.com/git-bug/git-bug/issues/995#issuecomment-1400483507"},"message":"\u003e I'm using version v0.8.0 so I'm not sure if it's gonna help 0.7.1\n\nindeed I had no output on my version.  So I upgraded git-bug, tried it, was alerted to migrate, did migration \n\n```\n/home/yoh/proj/misc/git-bug-migration/git-bug-migration --for-real  297.43s user 148.24s system 89% cpu 8:18.22 total\n```\n\nbut then got some odd error:\n\n```\n$\u003e git-bug version\ngit-bug version: v0.8.0-dev-064d866ca5\n\n$\u003e git bug bridge auth\nBuilding cache...\n      bug 0 / -1 [-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------]  0 %\n identity 0 / -1 [-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------]  0 %\nError: cannot create new index, path already exists\n\n$\u003e echo $?\n1\n```\n\nnot clear which path it talks about, probably not related really to `auth` but rather something about `git-bug`  since happens also for `git-bug bug`. [search](https://github.com/MichaelMure/git-bug/search?q=Error%3A+cannot+create+new+index%2C+path+already+exists) brought no hits.  My guess - migration didn't go \"well\"?","files":null}]}