{"author":{"id":"3998add589f6a09cf4bdf0e85e5481d2c48b8a757edd699a79a0c929ab5005db"},"ops":[{"type":3,"timestamp":1578164974,"nonce":"yyA8r9lz3chkY4OUnYzfbfOmqBY=","metadata":{"github-id":"MDEyOklzc3VlQ29tbWVudDU3MDgxMTIzMw==","github-url":"https://github.com/git-bug/git-bug/issues/286#issuecomment-570811233"},"message":"I looked in more details into this and I think what happened is that you used the bridge multiple times from different repository and pushed the bugs (not with a bridge, the normal push) to the git remote. When you push like this, git-bug doesn't know that it is pushing duplicates (they have different ID).\n\nLater when you do a `git bug pull` you pull again the same duplicates.\n\nThe problem is that you then end up with multiple bugs associated with the same Github issue and the bridge get confused.\n\nWhile this is not an actual problem in git-bug, the `github-import-error` made that easier to see and understand.\n\nNow what you need to do is to delete all those pushed bugs (see https://github.com/MichaelMure/git-bug/blob/master/Makefile#L46-L47) and everything should be back to normal.","files":null},{"type":4,"timestamp":1578164974,"nonce":"wPyCmlA0JccYuzTXOgQ/FRHt9Wo=","metadata":{"github-id":"MDExOkNsb3NlZEV2ZW50MjkyMjAwMTQ1MA=="},"status":2}]}