{"author":{"id":"8280890c639b421e6b9dcf2035bdf915ac11c1cf0e1f9dd00b2f6437faa22719"},"ops":[{"type":1,"timestamp":1586547958,"nonce":"RvvSrsOsGu+Rr5pCluclqFcUklo=","metadata":{"github-id":"MDU6SXNzdWU1OTgwNjE2NjU=","github-url":"https://github.com/git-bug/git-bug/issues/366","origin":"github"},"title":"Multiple bugs with gitlab bridge.","message":"Hi,\n\nPlaying with git- bug on a existing gitlab repository with a few existing issues on the vendor's bug tracker,  I ran trough the following errors:\n\nAfter having successfully configured the bridge I could import the gitlab issues as well as creating a couple of local issues with `git bug add`, so far so good. Then, I meet the following errors:\n* when doing again `git bug bridge pull`, issues are duplicated with new hashes. \n* nothing is exported when doing `git bug bridge push`.\n\nI've tested the bridge on a freshly created repo on gitlab, again the first steps goes well, but this time when doing `git bug bridge` a second time to test if duplicates arise, I got this crash:\n\n```\npanic: runtime error: index out of range [-1]                                                                                                        \n                                                                        \ngoroutine 51 [running]:       \ngithub.com/MichaelMure/git-bug/bridge/gitlab/iterator.(*issueIterator).Value(...)\n        /home/dtrckd/src/_sink/git-bug/bridge/gitlab/iterator/issue.go:38\ngithub.com/MichaelMure/git-bug/bridge/gitlab/iterator.(*Iterator).NextIssue(0xc0010ba000, 0xc000043dd0)\n        /home/dtrckd/src/_sink/git-bug/bridge/gitlab/iterator/iterator.go:86 +0x244\ngithub.com/MichaelMure/git-bug/bridge/gitlab.(*gitlabImporter).ImportAll.func1(0xc000260100, 0xc0000aed00, 0xc0010bc000)\n        /home/dtrckd/src/_sink/git-bug/bridge/gitlab/import.go:70 +0x547\ncreated by github.com/MichaelMure/git-bug/bridge/gitlab.(*gitlabImporter).ImportAll\n        /home/dtrckd/src/_sink/git-bug/bridge/gitlab/import.go:66 +0x146\n\n```\nSimilar scenario on Github seems to work fine.\n\nVersion:\ngit-bug version: 0.7.1-dev-28c3ee3b71\ngithub.com/xanzy/go-gitlab v0.29.0\ngo version go1.14.1 linux/amd64\n\nGitlab: 12.9.2 (self hosted)\nOS: Linux 4.19.0-8-amd64 / Debian 10 x86_64","files":null}]}