{"author":{"id":"1c0be4c7efe4cf70011d270a87e33999699eb0e9a5b12f84e0369f90dae3dacd"},"ops":[{"type":6,"timestamp":1616972107,"nonce":"yppasY1vJOKwQnyf1BM8kXiNjDg=","metadata":{"github-id":"MDE1OlVzZXJDb250ZW50RWRpdElzc3VlRWRpdDo1MTQ3MjI1MjM="},"target":"e30837e46fb4b1f9f27a3ef5c732f9a4a39a0106cbc7ef64f0a2b3e731f35122","message":"I am importing all the the issues from https://github.com/NixOS/nixpkgs. (Currently I am using git-bug from PR #585).\n\nWhen the import is finished the number of open and closed issues in git-bug and on github do not match. For example, github has 4298 open and 15884 closed issues in nixpkgs but git-bug shows the following:\n\n```          \n$ git-bug ls --status open | wc -l\n    4317\n$ git-bug ls --status closed | wc -l\n   15865\n```\n\nThis is caused by github having issues which are closed, but which seem to not have a ClosedEvent (as described in their API https://docs.github.com/en/graphql/reference/objects#closedevent). An example of such an issue is https://github.com/NixOS/nixpkgs/issues/90920. You can also see that when looking at the issue on the github website (the last link). Closed events usually have an issue-closed item in their timeline. This issue does not have that.","files":null},{"type":3,"timestamp":1616973391,"nonce":"scrV+40juou3NK1XrYbMXpUpnk0=","metadata":{"github-id":"MDEyOklzc3VlQ29tbWVudDgwODk3NjQxNw==","github-url":"https://github.com/git-bug/git-bug/issues/609#issuecomment-808976417"},"message":"Well, maybe the \"closed\" field on https://docs.github.com/en/graphql/reference/objects#issue in the Github API is supposed to handle that. I will have to try.","files":null}]}