{"author":{"id":"788581d40344e8e379d069717fdefef9e36e35fa2ae3837d616abc46caa14ea5"},"ops":[{"type":3,"timestamp":1619383466,"nonce":"q8KApya74HT9Y6+6vrgSYx3/hT0=","metadata":{"github-id":"MDEyOklzc3VlQ29tbWVudDgyNjM4NzI1Mg==","github-url":"https://github.com/git-bug/git-bug/issues/653#issuecomment-826387252"},"message":"Reverting [this line](https://github.com/MichaelMure/git-bug/blob/master/bug/op_edit_comment.go#L38) back to `commentId = op.target` seems to fix the issue. But I'm not sure if this is the right way to solve the problem. [This discussion](https://github.com/MichaelMure/git-bug/pull/631#pullrequestreview-635388561)  seems to be related, maybe reverting the line was just forgotten?","files":null}]}